napalm-automation-community/napalm-panos

- .travis.yml
- napalm_panos/__init__.py
- napalm_panos/panos.py
- pylama.ini
- requirements-dev.txt
- requirements.txt
- setup.cfg
- test/unit/TestDriver.py
new setup.cfg (rename pylama.ini)
pin to napalm-base
version fix in __init__.py
> pylama cleanup and pin napalm-base

- .github/ISSUE_TEMPLATE
- .github/PULL_REQUEST_TEMPLATE
- CONTRIBUTING
Addressing https://github.com/napalm-automation/napalm-panos/issues/11
> adding CONTRIBUTING, ISSUE_TEMPLATE, and PULL_REQUEST_TEMPLATE

- MANIFEST.in
- README.md
- napalm_panos/panos.py
- requirements-dev.txt
- test/unit/TestDriver.py
- test/unit/panos/mock_data/_show__config__candidate___candidate___config___show_.txt
- test/unit/panos/mock_data/running_config.txt
Adding get_config function. All getter tests passed.
> Adding get_config

- requirements.txt
> Use napalm-base>=0.18.0

- setup.py
> Release 0.2.1

- .travis.yml
- napalm_panos/panos.py
- setup.py
- test/unit/mocked_data/test_get_facts/normal/expected_result.json
> Adding is_alive method and py3 support

- .travis.yml
- setup.cfg
- tox.ini
Convert to use Tox; also old setup.cfg file no longer works with new version of coveralls (mutually exclusive error).
> Convert to use Tox

- napalm_panos/panos.py
- setup.py
- test/unit/mocked_data/test_get_lldp_neighbors/no_neighbor/_show__lldp__neighbors_all__neighbors___lldp___show_.xml
- test/unit/mocked_data/test_get_lldp_neighbors/no_neighbor/expected_result.json
> Releasing 0.4.1

- napalm_panos/panos.py
> add multiple imports

- napalm_panos/panos.py
> more import fixes

- napalm_panos/panos.py
- requirements.txt
- setup.py
- test/unit/TestDriver.py
- test/unit/conftest.py
- test/unit/test_getters.py
- tox.ini
> version bump

- setup.py
> pip 10 changes

- setup.cfg
> update setup.cfg for pytest api change

- napalm_panos/panos.py
Fixes https://github.com/napalm-automation-community/napalm-panos/issues/69
> Update lldp when single entry is shown

- napalm_panos/__init__.py
- napalm_panos/panos.py
- requirements-dev.txt
- requirements.txt
- setup.py
- test/unit/TestDriver.py
- test/unit/conftest.py
- test/unit/mocked_data/test_get_interfaces/normal/expected_result.json
> Add mtu to interface, run black, and fix tests

- napalm_panos/panos.py
> update splitlines on string of config

- .travis.yml
- napalm_panos/panos.py
- requirements-dev.txt
- requirements.txt
- tox.ini
> Kc updates

- README.md
- docs/supported_getters.md
- Adds a list of the supported getters
> Adds supported NAPALM getters doc

- napalm_panos/panos.py
- test/unit/mocked_data/test_get_interfaces/normal/_show__config__candidate___candidate___config___show_.xml
- test/unit/mocked_data/test_get_interfaces/normal/expected_result.json
- test/unit/mocked_data/test_get_interfaces/normal/running_config.xml
> Add Interface Descriptions

- README.md
- Found a minor update needed in the script
- Updated title
> Update script, change table title

- napalm_panos/panos.py
on line 627, add (sdwan\.) to the list of interfaces patterns
> Add support for sdwan interfaces
